// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr3e-PBE01ZaNKQB6L6bAyc9ZzTQZesiA',
    appId: '1:962883606461:web:4b1a0fb1ad90c3805964d4',
    messagingSenderId: '962883606461',
    projectId: 'chatting-362f3',
    authDomain: 'chatting-362f3.firebaseapp.com',
    storageBucket: 'chatting-362f3.appspot.com',
    measurementId: 'G-1YZ02W4QV5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArTZlhRTbjji_umN4xMO-LiSEfIITDjPM',
    appId: '1:962883606461:android:1e5e69f66c74ac965964d4',
    messagingSenderId: '962883606461',
    projectId: 'chatting-362f3',
    storageBucket: 'chatting-362f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXbeQEvo5DWWVnz5Ozhi8kLClLWZY8XBg',
    appId: '1:962883606461:ios:d87055e6870fa0485964d4',
    messagingSenderId: '962883606461',
    projectId: 'chatting-362f3',
    storageBucket: 'chatting-362f3.appspot.com',
    iosBundleId: 'com.voiceAiSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXbeQEvo5DWWVnz5Ozhi8kLClLWZY8XBg',
    appId: '1:962883606461:ios:d87055e6870fa0485964d4',
    messagingSenderId: '962883606461',
    projectId: 'chatting-362f3',
    storageBucket: 'chatting-362f3.appspot.com',
    iosBundleId: 'com.voiceAiSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBr3e-PBE01ZaNKQB6L6bAyc9ZzTQZesiA',
    appId: '1:962883606461:web:1a44734d985da0a45964d4',
    messagingSenderId: '962883606461',
    projectId: 'chatting-362f3',
    authDomain: 'chatting-362f3.firebaseapp.com',
    storageBucket: 'chatting-362f3.appspot.com',
    measurementId: 'G-G4FMJJVZJT',
  );
}
